LIBFT_PATH = src/libft

SRC += $(LIBFT_PATH)/ft_isalpha.c       \
	   $(LIBFT_PATH)/ft_memcpy.c        \
	   $(LIBFT_PATH)/ft_strlen.c        \
	   $(LIBFT_PATH)/ft_isascii.c       \
	   $(LIBFT_PATH)/ft_memmove.c       \
	   $(LIBFT_PATH)/ft_strncmp.c       \
	   $(LIBFT_PATH)/ft_strcmp.c		\
	   $(LIBFT_PATH)/ft_atoi.c          \
	   $(LIBFT_PATH)/ft_isdigit.c       \
	   $(LIBFT_PATH)/ft_memset.c        \
	   $(LIBFT_PATH)/ft_strnstr.c       \
	   $(LIBFT_PATH)/ft_strcpy.c		\
	   $(LIBFT_PATH)/ft_strjoin.c       \
	   $(LIBFT_PATH)/ft_strnjoin.c		\
	   $(LIBFT_PATH)/ft_bzero.c			\
	   $(LIBFT_PATH)/ft_isprint.c       \
	   $(LIBFT_PATH)/ft_strchr.c        \
	   $(LIBFT_PATH)/ft_strrchr.c       \
	   $(LIBFT_PATH)/ft_calloc.c        \
	   $(LIBFT_PATH)/ft_memchr.c        \
	   $(LIBFT_PATH)/ft_strdup.c        \
	   $(LIBFT_PATH)/ft_tolower.c       \
	   $(LIBFT_PATH)/ft_isalnum.c       \
	   $(LIBFT_PATH)/ft_memcmp.c        \
	   $(LIBFT_PATH)/ft_strlcat.c       \
	   $(LIBFT_PATH)/ft_strlcpy.c       \
	   $(LIBFT_PATH)/ft_toupper.c       \
	   $(LIBFT_PATH)/ft_substr.c        \
	   $(LIBFT_PATH)/ft_strtrim.c       \
	   $(LIBFT_PATH)/ft_split.c         \
	   $(LIBFT_PATH)/ft_itoa.c          \
	   $(LIBFT_PATH)/ft_strmapi.c       \
	   $(LIBFT_PATH)/ft_striteri.c      \
	   $(LIBFT_PATH)/ft_putchar_fd.c    \
	   $(LIBFT_PATH)/ft_putstr_fd.c     \
	   $(LIBFT_PATH)/ft_putendl_fd.c    \
	   $(LIBFT_PATH)/ft_double_free.c	\
	   $(LIBFT_PATH)/ft_putnbr_fd.c

OUT_DIRS += $(OUTPUT_DIR)/$(LIBFT_PATH)
