ENV_VARIABLE_PATH = src/env_variable_manager/

SRC += $(ENV_VARIABLE_PATH)environment_variables.c \
	   $(ENV_VARIABLE_PATH)set.c \
	   $(ENV_VARIABLE_PATH)set.c

OUT_DIRS += $(OUTPUT_DIR)/$(ENV_VARIABLE_PATH)
