CMD_PATH = src/cmd/

SRC += $(CMD_PATH)ft_cmdadd_back.c	\
	$(CMD_PATH)ft_cmdadd_front.c	\
	$(CMD_PATH)ft_cmdclear.c		\
	$(CMD_PATH)ft_cmdlast.c			\
	$(CMD_PATH)ft_cmdnew.c			\
	$(CMD_PATH)ft_cmdsize.c

OUT_DIRS += $(OUTPUT_DIR)/$(CMD_PATH)
