EXPANDS_PATH = src/expands/

SRC += $(EXPANDS_PATH)expands.c \
	   $(EXPANDS_PATH)expander_get.c  \
	   $(EXPANDS_PATH)expands_file_queries.c \
	   $(EXPANDS_PATH)expands_misc.c \
	   $(EXPANDS_PATH)expands_split.c

OUT_DIRS += $(OUTPUT_DIR)/$(EXPANDS_PATH)
