PIPEX_PATH = src/pipex/

SRC += $(PIPEX_PATH)exec_cmd.c		\
	$(PIPEX_PATH)execution_loop.c	\
	$(PIPEX_PATH)exit_processus.c	\
	$(PIPEX_PATH)open_fd.c			\
	$(PIPEX_PATH)here_doc.c         \
	$(PIPEX_PATH)here_doc_expands.c \
	$(PIPEX_PATH)here_doc_helpers.c \
	$(PIPEX_PATH)exec_path.c

OUT_DIRS += $(OUTPUT_DIR)/$(PIPEX_PATH)
