PARSER_PATH = src/token

SRC += $(PARSER_PATH)/tokeniser.c \
	   $(PARSER_PATH)/token_btree_parser.c \
	   $(PARSER_PATH)/token_parse.c \
	   $(PARSER_PATH)/token_push.c \
	   $(PARSER_PATH)/tokeniser_checks.c \
	   $(PARSER_PATH)/tokeniser_helpers.c \
	   $(PARSER_PATH)/token_setups.c \
	   $(PARSER_PATH)/syntax_checker.c \
	   $(PARSER_PATH)/syntax_checker_io_files.c \
	   $(PARSER_PATH)/syntax_checker_operands.c \
	   $(PARSER_PATH)/syntax_checker_parentheses.c

OUT_DIRS += $(OUTPUT_DIR)/$(PARSER_PATH)
