BUILTIN_PATH = src/builtin/

SRC += $(BUILTIN_PATH)expand.c \
	$(BUILTIN_PATH)builtin_list.c \
	$(BUILTIN_PATH)echo.c \
	$(BUILTIN_PATH)cd.c \
	$(BUILTIN_PATH)pwd.c \
	$(BUILTIN_PATH)export.c \
	$(BUILTIN_PATH)source.c \
	$(BUILTIN_PATH)unset.c

OUT_DIRS += $(OUTPUT_DIR)/$(BUILTIN_PATH)
