TTY_PATH = src/tty/

SRC += $(TTY_PATH)custom_prompt.c \
	   $(TTY_PATH)prompt_conditional.c \
	   $(TTY_PATH)prompt_expands.c \
	   $(TTY_PATH)prompt_helpers.c

OUT_DIRS += $(OUTPUT_DIR)/$(TTY_PATH)
