LIB_PATH := src/list

SRC += $(LIB_PATH)/get.c			\
	   $(LIB_PATH)/iterators.c	\
	   $(LIB_PATH)/list.c	\
	   $(LIB_PATH)/pop.c			\
	   $(LIB_PATH)/utils.c		\
	   $(LIB_PATH)/utils2.c

OUT_DIRS += $(OUTPUT_DIR)/$(LIB_PATH)
